### ISSUE TITLE
Better Handling for Common Host in Config

### ISSUE THREAD

**Issue by geoffreywiseman** [geoffreywiseman/tunnel-boring-machine#32]
If most of your tunnels are to a single host, the "host:" line gets a little irritating, there's a lot of repetition there. Would it be good to have a default host? Or should host be the topmost configuration element, and target names be under that?

```
dev.mycompany.com:
    dashboard:
        alias: db 
        forward: 3000
    qa: [8080,8443]
    prod:
        forward: 
           prod: [ 8080, 8443 ]
    staging:
            alias: stage
            forward: staging:8080
```

That would make it hard to support multiple hosts under a single target name in the future, but that's a far-flung possibility, and possibly not even a great idea.
